ecostage/mapbiomas

- app/assets/javascripts/components/map/map_canvas.es6.jsx
- app/assets/javascripts/vendor/leaflet-side-by-side.js
- app/assets/stylesheets/modules/_leaflet-side-by-side.scss
- app/assets/stylesheets/modules/_modules.scss
- app/views/pages/downloads.en.html.erb
- config/locales/en/views/layouts.yml
- config/locales/en/views/map.yml
- config/locales/pt-BR/views/map.yml
The green background of the label works well on both light and dark maps.
|Map|Land use and cover mapping|RGB mosaic|
|---|---|---|
|Esri Image|![captura de tela de 2017-08-07 10-24-51](https://user-images.githubusercontent.com/4391802/29028485-e10b2ed0-7b5a-11e7-8d5c-2b1a18a05562.png)|![captura de tela de 2017-08-07 10-26-21](https://user-images.githubusercontent.com/4391802/29028555-121c270e-7b5b-11e7-82b2-9d181909bb44.png)|
|Esri Roads|![captura de tela de 2017-08-07 10-28-56](https://user-images.githubusercontent.com/4391802/29028693-7e52d4fe-7b5b-11e7-80f0-bfac317d1f40.png)|![captura de tela de 2017-08-07 10-27-53](https://user-images.githubusercontent.com/4391802/29028624-4c75cc34-7b5b-11e7-914e-bc9f22c31b24.png)|
|Esri Relief|![captura de tela de 2017-08-07 …
> Create labels for LeafletSideBySide

- app/views/pages/database/mapbiomas_collection.en.html.erb
- app/views/pages/database/reference_maps.en.html.erb
> Add text to Refence Maps and MapBiomas Collection pages in English

- app/assets/javascripts/components/controls/territory.es6.jsx
- app/assets/javascripts/components/map/map.es6.jsx
- app/assets/javascripts/components/map/map_canvas.es6.jsx
When I select a territory for the first time, I need to see the data **restricted to that territory**
> Fix request after first territory select

- app/assets/javascripts/components/charts/transitions.es6.jsx
- app/assets/javascripts/components/map/map.es6.jsx
- app/assets/javascripts/components/modals/transitions_chart_and_matrix.es6.jsx
- app/assets/javascripts/components/panels/transitions/auxiliar_controls.es6.jsx
- app/assets/javascripts/components/panels/transitions/menu.es6.jsx
- app/assets/stylesheets/layout/_transitions-control.scss
- config/locales/en/views/map.yml
- config/locales/pt-BR/views/map.yml
> Change from a particular transition to the general ones

- app/views/pages/team.en.html.erb
- app/views/pages/team.pt-BR.html.erb
> change names on caatinga team

- app/assets/javascripts/components/menu/menu_control.es6.jsx
- app/assets/stylesheets/base/_variables.scss
- app/assets/stylesheets/layout/_header.scss
- app/assets/stylesheets/layout/_menu.scss
- app/views/layouts/devise.html.erb
|Before|After|
|-|-|
|![captura de tela de 2017-09-29 17-07-53](https://user-images.githubusercontent.com/4391802/31034150-2ddd5122-a539-11e7-8c48-b55f8c4b74a5.png)|![captura de tela de 2017-09-29 17-10-40](https://user-images.githubusercontent.com/4391802/31034209-7058487c-a539-11e7-95fa-7e429f724e50.png)|
> Header improvements

- app/assets/javascripts/components/stats/stats.es6.jsx
- app/assets/stylesheets/layout/_common.scss
- app/assets/stylesheets/layout/_footer.scss
- app/assets/stylesheets/layout/_map.scss
- app/assets/stylesheets/layout/_page.scss
- app/views/layouts/_footer.html.erb
- app/views/stats/show.html.erb
|Before|After|
|-|-|
|![captura de tela de 2017-09-29 17-22-21](https://user-images.githubusercontent.com/4391802/31034593-1982f680-a53b-11e7-8aca-8c8513141cac.png)|![captura de tela de 2017-09-29 17-22-36](https://user-images.githubusercontent.com/4391802/31034592-197fc9a6-a53b-11e7-9816-9b270ebf5279.png)|
|300px|700px|1200px|
|-|-|-|
|![captura de tela de 2017-09-29 17-15-36](https://user-images.githubusercontent.com/4391802/31034407-5fd6a862-a53a-11e7-9fe0-c356c8af7f06.png)|![captura de tela de 2017-09-29 17-15-59](https://user-images.githubusercontent.com/4391802/31034408-5ff6395c-a53a-11e7-8cc8-ff3eab684763.png)|![captura de tela de 2017-09-29 17-19-23](https://user-images.githubusercontent.com/4391802/31034473-aabd5f6a-a53a-11e7-93ed-5ca39f515faa.png)|
> Footer improvements

- app/assets/javascripts/components/charts/transitions.es6.jsx
- app/assets/javascripts/components/controls/classification.es6.jsx
- app/assets/javascripts/components/controls/transitions_layers.es6.jsx
- app/assets/javascripts/components/map/map.es6.jsx
- app/assets/javascripts/components/map/my_maps.es6.jsx
- app/assets/javascripts/components/menu/menu_control.es6.jsx
- app/assets/javascripts/components/modals/transitions_chart_and_matrix.es6.jsx
- app/assets/javascripts/components/panels/main_menu.es6.jsx
- app/assets/javascripts/components/panels/transitions/auxiliar_controls.es6.jsx
- app/assets/javascripts/components/panels/transitions/labels.es6.jsx
- app/assets/stylesheets/layout/_map-panel.scss
- app/assets/stylesheets/layout/_my_maps.scss
- app/controllers/map_controller.rb
- app/views/layouts/iframe.html.erb
- app/views/map/my_maps.html.erb
- config/locales/en/views/iframe.yml
- config/locales/en/views/my_maps.yml
- config/locales/pt-BR/views/iframe.yml
- config/locales/pt-BR/views/my_maps.yml
- config/routes.rb
> Map iframe

- app/assets/javascripts/components/menu/menu_control.es6.jsx
- app/assets/stylesheets/base/_base.scss
- app/assets/stylesheets/base/_flashes.scss
- app/assets/stylesheets/base/_variables.scss
- app/assets/stylesheets/layout/_credentials.scss
- app/assets/stylesheets/layout/_forms.scss
- app/assets/stylesheets/layout/_layout.scss
- app/assets/stylesheets/layout/_profile.scss
- app/controllers/users_controller.rb
- app/models/user.rb
- app/views/devise/sessions/new.html.erb
- app/views/users/profile.html.erb
- config/locales/en/models/user.yml
- config/locales/en/views/users.yml
- config/locales/pt-BR/models/user.yml
- config/locales/pt-BR/views/users.yml
- config/routes.rb
- db/migrate/20171109012553_add_profile_data_to_user.rb
- db/schema.rb
> Create Profile page for user

- app/views/pages/methodology.en.html.erb
- app/views/pages/methodology.pt-BR.html.erb
Requisitado via e-mail por Tasso (01/12/2017 - 13:17)
> update atbd file for costal zone

- app/assets/javascripts/components/menu/menu_control.es6.jsx
- app/assets/stylesheets/base/_variables.scss
- app/assets/stylesheets/layout/_menu.scss
- config/locales/en.yml
- config/locales/pt-BR.yml
> Add label new in menu

- app/views/pages/downloads.en.html.erb
- app/views/pages/downloads.pt-BR.html.erb
- app/views/pages/legenda.en.html.erb
- app/views/pages/legenda.pt-BR.html.erb
https://trello.com/c/IHFr9Ib1/9-codigos-de-legenda
> legend page

- config/locales/en/views/map.yml
- config/locales/pt-BR/views/map.yml
https://trello.com/c/TvZJCgvb/11-corre%C3%A7%C3%A3o-termos-dashboard-cobertura
> update map texts

- app/views/pages/scripts.en.html.erb
- app/views/pages/scripts.pt-BR.html.erb
https://trello.com/c/gHWR9pap/14-scripts
> update text to collection 2.3

- app/assets/javascripts/components/controls/zoom_and_opacity.es6.jsx
- app/assets/javascripts/components/map/map.es6.jsx
- app/assets/javascripts/components/modals/modal.es6.jsx
- app/assets/javascripts/components/modals/tutorial.es6.jsx
- app/assets/stylesheets/layout/_map-panel.scss
- app/assets/stylesheets/layout/_map.scss
- config/locales/en/views/map.yml
- config/locales/pt-BR/views/map.yml
> Create tutorials for Coverage and Transitions pages

- app/views/pages/methodology.en.html.erb
- app/views/pages/methodology.pt-BR.html.erb
https://trello.com/c/7DFXgaBr/24-atbds
> update pampa and cerrado links

- app/views/pages/mapa-mural.en.html.erb
- app/views/pages/mapa-mural.pt-BR.html.erb
https://trello.com/c/KXtIJlH6/29-atualizar-mapa-mural
> update links for tif and pdf

- app/views/pages/methodology.en.html.erb
- app/views/pages/methodology.pt-BR.html.erb
https://trello.com/c/7DFXgaBr/24-atbds#comment-5a52611ed8a46ffd3765d1dc
> update amazon atbd file

- app/views/pages/database/mapbiomas_collection.en.html.erb
- app/views/pages/database/mapbiomas_collection.pt-BR.html.erb
https://trello.com/c/iEIBsUoG/12-download-de-mapas-da-colecao-23#comment-5a4ff6af5dcc80301e80d850
> fix text at collection page

- app/views/pages/analysis.en.html.erb
https://trello.com/c/HPYbpgXu/22-p%C3%A1gina-an%C3%A1lise-de-acur%C3%A1cia-em-ingl%C3%AAs
> add english analysis page

- app/assets/javascripts/components/menu/menu_control.es6.jsx
- app/views/pages/announcement_note_collection2_3.en.erb
- app/views/pages/announcement_note_collection2_3.pt-BR.erb
- app/views/pages/home.en.html.erb
- app/views/pages/home.pt-BR.html.erb
- config/locales/en/views/layouts.yml
- config/locales/pt-BR/views/layouts.yml
https://trello.com/c/3Eo5PMRE/37-nota-de-anuncio-da-colecao-23
> add announcement note of collection 2.3 and submenu 'news'

- app/assets/stylesheets/layout/_footer.scss
- app/views/layouts/_footer_iframe.html.erb
- app/views/layouts/iframe.html.erb
https://trello.com/c/N7g4ELB0/39-iframe-no-iframe-alterar-o-rodap%C3%A9
> change footer when in iframe

- config/locales/pt-BR/views/stats.yml
> add ha legend

- app/views/pages/scripts.en.html.erb
- app/views/pages/scripts.pt-BR.html.erb
https://trello.com/c/Ac0Cat6d/48-auste-de-texto-em-downloads#comment-5a5bdb6dd19b106a1c810260
> update text at scripts page

- app/views/pages/accuracy-analysis.en.html.erb
- app/views/pages/accuracy-analysis.pt-BR.html.erb
(requisição feita pelo Tasso via e-mail)
> update text at accuracy analysis page

- app/views/pages/scripts.en.html.erb
- app/views/pages/scripts.pt-BR.html.erb
https://trello.com/c/GjlHayq1/53-atualizar-link-e-texto-na-p%C3%A1gina-de-scripts
> update texts at scripts page

- app/assets/javascripts/lib/territories.es6
> Improve territory label for select

- app/assets/javascripts/components/map/my_maps.es6.jsx
- config/locales/en/views/my_maps.yml
- config/locales/pt-BR/views/my_maps.yml
> Validate map title presence

- app/assets/javascripts/components/controls/classification.es6.jsx
> Enable classification selection to iframes

- app/assets/javascripts/components/modals/stats.es6.jsx
- app/assets/javascripts/components/modals/transitions_chart_and_matrix.es6.jsx
- app/assets/stylesheets/layout/_layout.scss
- app/assets/stylesheets/layout/_map.scss
- app/assets/stylesheets/layout/_stats-modal.scss
- app/assets/stylesheets/layout/_transitions-control.scss
- app/assets/stylesheets/layout/_transitions-matrix.scss
|Before|After|
|---------|------|
|![captura de tela de 2018-01-29 09-52-15](https://user-images.githubusercontent.com/4391802/35511392-d67d399c-04e2-11e8-888b-13bc16312beb.png)|![captura de tela de 2018-01-29 09-50-09](https://user-images.githubusercontent.com/4391802/35511338-9401a3a0-04e2-11e8-8949-309e22d3820f.png)|
|![captura de tela de 2018-01-29 09-52-29](https://user-images.githubusercontent.com/4391802/35511393-d69d536c-04e2-11e8-8ea4-87aedcc26083.png)|![captura de tela de 2018-01-29 09-50-23](https://user-images.githubusercontent.com/4391802/35511339-941ab296-04e2-11e8-9824-40c6a4ec2f1f.png)|
|![captura de tela de 2018-01-29 09-52-45](https://user-images.githubusercontent.com/4391802/35511394-d6b5debe-04e2-11e8-93d5-4c78b2c41444.png)|![captura de tela de 2018-01-29 …
> Improve modal for coverage and transitions data

- Gemfile
- Gemfile.lock
- app/assets/javascripts/components/menu/menu_control.es6.jsx
- app/controllers/application_controller.rb
- app/controllers/users_controller.rb
- app/models/user.rb
- app/policies/application_policy.rb
- app/policies/user_policy.rb
- app/views/layouts/_header.html.erb
- app/views/users/_user.html.erb
- app/views/users/registered.html.erb
- config/locales/en.yml
- config/locales/en/models/user.yml
- config/locales/en/views/users.yml
- config/locales/pt-BR.yml
- config/locales/pt-BR/models/user.yml
- config/locales/pt-BR/views/users.yml
- config/routes.rb
- db/migrate/20180129020055_add_role_to_user.rb
- db/schema.rb
> Create registered users page

- app/assets/javascripts/components/users/registered.jsx
- app/assets/javascripts/index.js
- app/assets/stylesheets/layout/_layout.scss
- app/assets/stylesheets/layout/_registered_users.scss
- app/controllers/users_controller.rb
- app/views/users/_user.html.erb
- app/views/users/registered.html.erb
- config/locales/en/views/users.yml
- config/locales/pt-BR/views/users.yml
- package.json
- yarn.lock
> Order registered users

- app/assets/javascripts/components/controls/territory.es6.jsx
- app/assets/stylesheets/layout/_layout.scss
- app/assets/stylesheets/layout/_territories-control.scss
- app/assets/stylesheets/modules/_react-select.scss
- app/assets/stylesheets/modules/_react-tabs.scss
- config/locales/en/views/map.yml
- config/locales/pt-BR/views/map.yml
> Add drainage basins statistics

- app/assets/javascripts/components/controls/territory.es6.jsx
- app/assets/stylesheets/layout/_map-panel.scss
- app/assets/stylesheets/modules/_react-tabs.scss
> Add tabs for indigenous lands and conservation units in territory control

- app/assets/javascripts/components/charts/quality.es6.jsx
- app/assets/javascripts/components/map/map.es6.jsx
- app/assets/javascripts/components/map/map_canvas.es6.jsx
- app/assets/javascripts/components/panels/quality/labels.es6.jsx
- app/presenters/map_presenter.rb
- config/locales/en/views/map.yml
- config/locales/pt-BR/views/map.yml
**Disclaimer**: new labels and pie chart data will be provided later.
> Quality layer

- app/models/terras_api.rb
> Cache all terras api request

- app/assets/javascripts/components/controls/territory.es6.jsx
- app/assets/javascripts/components/map/map.es6.jsx
- app/assets/stylesheets/layout/_territories-control.scss
- app/presenters/map_presenter.rb
- config/locales/en/views/map.yml
- config/locales/pt-BR/views/map.yml
> Improve territory control

- app/assets/javascripts/components/map/map.es6.jsx
- app/assets/javascripts/components/map/map_canvas.es6.jsx
- app/assets/javascripts/components/modals/point.es6.jsx
- app/assets/stylesheets/layout/_map-panel.scss
- app/presenters/map_presenter.rb
- config/initializers/settings.rb
> Add year control to point modal

- app/assets/javascripts/components/map/map.es6.jsx
- app/assets/javascripts/components/map/map_canvas.es6.jsx
- app/assets/javascripts/components/modals/point.es6.jsx
- app/assets/javascripts/components/modals/transitions_chart_and_matrix.es6.jsx
- app/assets/javascripts/components/panels/transitions/matrix.es6.jsx
- app/assets/stylesheets/layout/_map-panel.scss
- app/assets/stylesheets/layout/_transitions-modal.scss
- app/presenters/map_presenter.rb
- config/initializers/settings.rb
- config/locales/en/views/map.yml
- config/locales/pt-BR/views/map.yml
> Group transitions data by level

- app/assets/javascripts/components/map/map.es6.jsx
- app/assets/javascripts/components/map/map_canvas.es6.jsx
- app/assets/javascripts/components/panels/quality/auxiliar_controls.es6.jsx
- app/assets/javascripts/components/panels/transitions/auxiliar_controls.es6.jsx
> Create quality auxiliar controls

- app/assets/javascripts/components/charts/coverage/line.es6.jsx
- app/assets/javascripts/components/charts/coverage/pie.es6.jsx
- app/assets/javascripts/components/controls/car.es6.jsx
- app/assets/javascripts/components/map/map.es6.jsx
- app/assets/javascripts/components/map/map_canvas.es6.jsx
- app/assets/javascripts/components/panels/coverage/auxiliar_controls.es6.jsx
- app/assets/javascripts/components/panels/coverage/menu.es6.jsx
- app/assets/javascripts/lib/api.es6
- app/controllers/api/car_controller.rb
- app/models/terras_api.rb
- app/presenters/map_presenter.rb
- config/locales/en/views/map.yml
- config/locales/pt-BR/views/map.yml
- config/routes.rb
> Car coverage

- app/assets/javascripts/components/map/map_canvas.es6.jsx
- app/presenters/map_presenter.rb
|Before|After|
|---|---|
|![captura de tela de 2018-08-23 14-42-20](https://user-images.githubusercontent.com/4391802/44542495-58a81e80-a6e3-11e8-9060-7a9e35170131.png)|![captura de tela de 2018-08-23 14-41-34](https://user-images.githubusercontent.com/4391802/44542464-3f9f6d80-a6e3-11e8-807f-1234659c8740.png)|
> Layers update

- app/assets/javascripts/components/controls/transitions_layers.es6.jsx
- app/assets/javascripts/components/map/map.es6.jsx
- config/locales/en/views/map.yml
- config/locales/pt-BR/views/map.yml
|Before|After|
|---|---|
|![captura de tela de 2018-08-29 12-29-15](https://user-images.githubusercontent.com/4391802/44798415-ce026c00-ab87-11e8-8343-53c9d181f03a.png)|![captura de tela de 2018-08-29 12-28-33](https://user-images.githubusercontent.com/4391802/44798414-ce026c00-ab87-11e8-915b-d4a8a21b9304.png)|
> Update transition labels

- app/assets/javascripts/components/controls/infrastructure/hierarchy_category.es6.jsx
- app/assets/javascripts/components/controls/infrastructure/infrastructure.es6.jsx
- app/assets/javascripts/components/map/map.es6.jsx
- app/assets/javascripts/components/map/map_canvas.es6.jsx
- app/assets/javascripts/components/panels/coverage/auxiliar_controls.es6.jsx
- app/assets/javascripts/components/panels/quality/auxiliar_controls.es6.jsx
- app/assets/javascripts/components/panels/transitions/auxiliar_controls.es6.jsx
- app/assets/javascripts/lib/collapsible.es6.jsx
- config/locales/en/views/map.yml
- config/locales/pt-BR/views/map.yml
> Create buffer select for infrastructure

- app/assets/stylesheets/layout/_header.scss
- app/assets/stylesheets/layout/_menu.scss
- app/assets/stylesheets/layout/_team.scss
- app/views/layouts/_footer.html.erb
- app/views/layouts/_header.html.erb
- app/views/pages/team.pt-BR.html.erb
> Moving language selector for header

- app/assets/javascripts/components/charts/coverage/line.es6.jsx
- app/assets/javascripts/components/charts/coverage/pie.es6.jsx
- app/assets/javascripts/components/controls/car.es6.jsx
- app/assets/javascripts/components/controls/infrastructure/infrastructure.es6.jsx
- app/assets/javascripts/components/map/map.es6.jsx
- app/assets/javascripts/components/panels/auxiliar_controls.jsx
- app/assets/javascripts/components/panels/coverage/menu.es6.jsx
- app/assets/javascripts/components/stats/stats.es6.jsx
- config/locales/en/views/stats.yml
- config/locales/pt-BR/views/stats.yml
> Coverage select
